/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-06-15 16:58:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1750003340757L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1750004124243L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\" crossorigin=\"anonymous\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-warning\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/\">Employee</a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"navbar-nav mx-auto mb-2 mb-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"employeelist.jsp\">Employee List</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"addemployee.jsp\">Add Employee</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <form action=\"search.jsp\" method=\"post\" class=\"d-flex\" role=\"search\">\r\n");
      out.write("                        <input name=\"name\" id=\"name\" class=\"form-control me-2 bg-warning border-danger\" type=\"search\" placeholder=\"Search employee...\" aria-label=\"Search\"/>\r\n");
      out.write("                        <button class=\"btn btn-danger\" type=\"submit\">Search</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("<title>About | Employee JSP Project</title>\r\n");
      out.write("<div class=\"container my-3 px-0 border border-danger rounded px-5\">\r\n");
      out.write("    <div class=\"row my-3\">\r\n");
      out.write("        <h1 class=\"text-warning text-center\">About Us</h1>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"lead\">Employee is not just our name ? it?s our mission.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <p>\r\n");
      out.write("            At <strong>Employee</strong>, we exist to redefine the relationship between people and the workplace. We are a purpose-driven company committed to building a world where every employee feels empowered, supported, and equipped to succeed in an evolving professional landscape. Our goal is simple but transformative: to elevate every employee, everywhere.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>\r\n");
      out.write("            Founded on the belief that people are the most powerful engine behind business success, Employee is pioneering a new standard for how companies attract, engage, develop, and retain talent. From startups to global enterprises, we provide next-generation workforce solutions designed to unlock the full potential of every individual and the collective strength of every team.\r\n");
      out.write("        </p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>Our Vision</h2>\r\n");
      out.write("        <p>To create a global ecosystem where every employee is valued, every voice is heard, and every opportunity is accessible ? regardless of industry, geography, or background.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>Our Mission</h2>\r\n");
      out.write("        <p>To empower organizations and individuals by delivering innovative, employee-centric tools, technologies, and strategies that transform the workplace into a space of growth, inclusion, and excellence.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>What We Do</h2>\r\n");
      out.write("        <p>Employee offers a comprehensive suite of services and technologies that cover the full employee lifecycle. We are a one-stop solution for modern HR challenges ? bridging the gap between human needs and business goals with precision, empathy, and innovation.</p>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"list-group list-group-flush mt-3\">\r\n");
      out.write("            <li class=\"list-group-item\"><strong>Talent Acquisition & Recruitment Solutions:</strong> Streamlined, data-driven hiring processes that prioritize quality, cultural fit, and long-term success.</li>\r\n");
      out.write("            <li class=\"list-group-item\"><strong>Employee Experience Platforms:</strong> Customizable platforms that foster communication, recognition, wellness, and engagement from day one.</li>\r\n");
      out.write("            <li class=\"list-group-item\"><strong>Performance & Productivity Tools:</strong> From goal setting to real-time feedback and growth planning, we help employees thrive at every stage of their journey.</li>\r\n");
      out.write("            <li class=\"list-group-item\"><strong>HR Analytics & People Intelligence:</strong> Unlock the power of your workforce with deep insights into performance, engagement, and organizational health.</li>\r\n");
      out.write("            <li class=\"list-group-item\"><strong>Diversity, Equity, and Inclusion Programs:</strong> Practical frameworks and tools that ensure your workplace reflects the values of fairness and belonging.</li>\r\n");
      out.write("            <li class=\"list-group-item\"><strong>Learning & Development Systems:</strong> Future-ready learning programs that align employee growth with company success.</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>Our Philosophy: People First, Always</h2>\r\n");
      out.write("        <p>At Employee, we put people at the heart of everything we do. We believe that a company?s success is ultimately measured by the well-being and performance of its people.</p>\r\n");
      out.write("        <p>We are champions of ethical leadership, empathetic design, and responsible innovation. In every product we build and every service we offer, we ask ourselves: <em>Does this help employees flourish?</em></p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>Who We Serve</h2>\r\n");
      out.write("        <p>Employee proudly partners with organizations across sectors ? from tech to healthcare, education to finance, manufacturing to nonprofit ? helping them build resilient, people-focused cultures.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>Our Team</h2>\r\n");
      out.write("        <p>Behind Employee is a global team of HR experts, designers, software developers, behavioral scientists, and organizational strategists ? all driven by one shared belief: that employees deserve more.</p>\r\n");
      out.write("        <p>We operate with agility, empathy, and a deep commitment to excellence. We bring together decades of cross-industry experience, unified by a common goal: helping people work better, together.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-5\">\r\n");
      out.write("        <h2>The Future of Work Starts Here</h2>\r\n");
      out.write("        <p>In a time of massive workplace transformation, Employee stands at the forefront ? a trusted guide for businesses navigating change and a champion for employees seeking meaning and mobility in their careers.</p>\r\n");
      out.write("        <p>We?re building more than tools. We?re building trust, community, and a future where work is a source of fulfillment, not just a means to an end.</p>\r\n");
      out.write("        <p><strong>Employee</strong> is not just a company. It?s a movement. <br> <em>Join us.</em></p>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid bg-warning\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <footer class=\"py-3\">\r\n");
      out.write("            <ul class=\"nav justify-content-center border-bottom pb-3 mb-3\">\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"index.jsp\" class=\"nav-link px-2 text-body-secondary\">Home</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"employeelist.jsp\" class=\"nav-link px-2 text-body-secondary\">Employee List</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"addemployee.jsp\" class=\"nav-link px-2 text-body-secondary\">Add Employee</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"contact.jsp\" class=\"nav-link px-2 text-body-secondary\">Contact</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"about.jsp\" class=\"nav-link px-2 text-body-secondary\">About</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p class=\"text-center text-body-secondary\">Employee © 2025 Company Limited</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
