/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-06-17 07:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Employee;

public final class editemployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1750141700668L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1750144198943L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.Employee");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Employee e = (Employee) request.getAttribute("employee");

      out.write("\n");
      out.write("\n");
      out.write("<title>Update Employee - EMS</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\" integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-warning\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"/\"><h5><i class=\"fa-solid fa-users-gear\"></i> EMS</h5></a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                    <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"/\"><i class=\"fa-solid fa-house\"></i> Home</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"allemployees.jsp\"><i class=\"fa-solid fa-users\"></i> All Employees</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"addemployee.jsp\"><i class=\"fa-solid fa-user-plus\"></i> Add Employee</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"searchemployee.jsp\"><i class=\"fa-solid fa-magnifying-glass\"></i> Search Employee</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"contactus.jsp\"><i class=\"fa-solid fa-phone\"></i> Contact Us</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"aboutus.jsp\"><i class=\"fa-solid fa-users-gear\"></i> About Us</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"conatiner-fluid px-3\">\n");
      out.write("    <div class=\"container my-3 p-0 bg-warning border border-warning rounded\">\n");
      out.write("        <h4 class=\"text-center my-3\"><i class=\"fa-solid fa-user-secret\"></i> Update Employee</h4>\n");
      out.write("        <div class=\"conatiner-fluid bg-light m-0 px-5 py-3\">\n");
      out.write("\n");
      out.write("            <form action=\"employeeservlet\" method=\"post\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">ID</label>\n");
      out.write("                            <input name=\"id\" type=\"hidden\" id=\"id\" value=\"");
      out.print(e.getId());
      out.write("\">\n");
      out.write("                            <input name=\"action\" type=\"hidden\" value=\"update\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" value=\"");
      out.print(e.getId());
      out.write("\" disabled>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Name</label>\n");
      out.write("                            <input name=\"name\" type=\"text\" class=\"form-control\" id=\"name\" value=\"");
      out.print(e.getName());
      out.write("\" placeholder=\"Your name\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Email</label>\n");
      out.write("                            <input name=\"email\" type=\"email\" class=\"form-control\" id=\"email\" value=\"");
      out.print(e.getEmail());
      out.write("\" placeholder=\"Your email\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Phone</label>\n");
      out.write("                            <input name=\"phone\" type=\"text\" class=\"form-control\" id=\"phone\" value=\"");
      out.print(e.getPhone());
      out.write("\" placeholder=\"Your phone\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Designation</label>\n");
      out.write("                            <select name=\"designation\" class=\"form-select\" id=\"designation\">\n");
      out.write("                                <option value=\"CEO\" ");
      out.print( "CEO".equals(e.getDesignation()) ? "selected" : "" );
      out.write(">CEO</option>\n");
      out.write("                                <option value=\"Project Manager\" ");
      out.print( "Project Manager".equals(e.getDesignation()) ? "selected" : "" );
      out.write(">Project Manager</option>\n");
      out.write("                                <option value=\"Senior Software Developer\" ");
      out.print( "Senior Software Developer".equals(e.getDesignation()) ? "selected" : "" );
      out.write(">Senior Software Developer</option>\n");
      out.write("                                <option value=\"Junior Software Developer\" ");
      out.print( "Junior Software Developer".equals(e.getDesignation()) ? "selected" : "" );
      out.write(">Junior Software Developer</option>\n");
      out.write("                                <option value=\"Intern Software Developer\" ");
      out.print( "Intern Software Developer".equals(e.getDesignation()) ? "selected" : "" );
      out.write(">Intern Software Developer</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Salary</label>\n");
      out.write("                            <input name=\"salary\" type=\"number\" class=\"form-control\" id=\"salary\" value=\"");
      out.print(e.getSalary());
      out.write("\" placeholder=\"Your salary\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\">Gender</label>\n");
      out.write("                            <div class=\"form-check\">\n");
      out.write("                                <input name=\"gender\" class=\"form-check-input\" type=\"radio\" id=\"gender\" value=\"Male\" ");
      out.print( "Male".equals(e.getGender()) ? "checked" : "" );
      out.write(" >\n");
      out.write("                                <label class=\"form-check-label\" for=\"radioDefault1\">\n");
      out.write("                                    Male\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-check\">\n");
      out.write("                                <input name=\"gender\" class=\"form-check-input\" type=\"radio\" id=\"gender\" value=\"Female\" ");
      out.print( "Female".equals(e.getGender()) ? "checked" : "" );
      out.write(">\n");
      out.write("                                <label class=\"form-check-label\" for=\"radioDefault1\">\n");
      out.write("                                    Female\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row my-5\">\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 d-flex justify-content-center aling-items-center\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success mx-3\">Update</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container-fluid bg-warning\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <footer class=\"d-flex flex-wrap justify-content-between align-items-center pt-3\">\n");
      out.write("            <div class=\"col-md-4 d-flex align-items-center\">\n");
      out.write("                <a href=\"/\" class=\"mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1\" aria-label=\"Bootstrap\">\n");
      out.write("                    <p><i class=\"fa-solid fa-users-gear\"></i> EMS © 2025 Company, Inc</p>\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"nav col-md-4 justify-content-end list-unstyled d-flex\">\n");
      out.write("                <li class=\"ms-3\">\n");
      out.write("                    <a class=\"text-body-secondary\" href=\"#\">\n");
      out.write("                        <h5><i class=\"fa-brands fa-facebook\"></i></h5>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"ms-3\">\n");
      out.write("                    <a class=\"text-body-secondary\" href=\"#\">\n");
      out.write("                        <h5><i class=\"fa-brands fa-twitter\"></i></h5>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"ms-3\">\n");
      out.write("                    <a class=\"text-body-secondary\" href=\"#\">\n");
      out.write("                        <h5><i class=\"fa-brands fa-instagram\"></i></h5>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"ms-3\">\n");
      out.write("                    <a class=\"text-body-secondary\" href=\"#\">\n");
      out.write("                        <h5><i class=\"fa-brands fa-github\"></i></h5>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"ms-3\">\n");
      out.write("                    <a class=\"text-body-secondary\" href=\"#\">\n");
      out.write("                        <h5><i class=\"fa-brands fa-youtube\"></i></h5>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
